### ISSUE TITLE
Docker compose fails

### ISSUE THREAD

**Issue by jankolkmeier** [AgentsUnited/daf#3]
setting up docker with ```docker-compose build``` fails for me with the following result:

```
mongodb uses an image, skipping
Building controller
Step 1/6 : FROM phusion/baseimage:latest
ERROR: Service 'controller' failed to build: manifest for phusion/baseimage:latest not found: manifest unknown: manifest unknown
```

Without really knowing what it means, I've applied the fix suggested [here](https://stackoverflow.com/questions/63229267/service-certbot-failed-to-build-manifest-for-phusion-baseimagelatest-not-fou) to ```daf-controller/Dockerfile```, ```dgep/Dockerfile``` ```utterance_generator/Dockerfile```, which seems to have solved the issue.

**Comment by marksnaith** [comment]
Now resolved by using `phusion/baseimage:latest-amd64` in the Dockerfile.
